name: "LatchsUnenchanter"
version: ${project.version}
authors: [Latch,mfnalex]
main: Latch.Unenchanter.Unenchanter
api-version: 1.19
softdepend: [Vault, PlaceholderAPI]
commands:
  unenchant:
    description: Unenchant
    usage: /unenchant
    permission: ur.command.unenchant
permissions:
  ur.command.reload:
    description: Reloads the configuration file
