name: UnenchanterRedux
version: 0.0.5
author: Latch
main: Latch.UnenchanterRedux.UnenchanterRedux
api-version: 1.17
softdepend: [Vault]
commands:
  unenchant:
    description: Unenchant
    usage: /unenchant
    permission: ur.command.unenchant